### ISSUE TITLE
Readme wrong link

### ISSUE THREAD

**Issue by Dervisevic** [kornosaurus/generator-diversity-component#15]
In the readme generated, there is a command for registering the component, it's faulty, example:

`curl -X POST -d repo_url=https://git.diversity.io/tws-newsletter-subscribe/tws-newsletter-subscribe.git api.diversity.io/components/tws-newsletter-subscribe/register`

But should in fact use the namespace instead of the component name twice:

`curl -X POST -d repo_url=https://git.diversity.io/textalk-webshop-native-components/tws-newsletter-subscribe.git api.diversity.io/components/tws-newsletter-subscribe/register`

**Comment by kornosaurus** [comment]
Since the ds-api update this is no longer a issue
